In [1]:
r=.3
import math

In [2]:
print(math.pi)

3.141592653589793


In [3]:
A=math.pi*r*r
print(A)

0.2827433388230814


math.max(4,5)

In [4]:
from math import pi
A=pi*r*r
print(A)

0.2827433388230814


In [ ]:
math.A.B.C.my_const*r*r
from math.A.B.C import my_const
my_const*r*r

In [6]:
import math
res=math.sqrt(10)
print(res)

3.1622776601683795


In [7]:
from  math import sqrt
a=sqrt(10)
print(a)

3.1622776601683795


In [8]:
import numpy as np
length=[2,4,6,8]
width=[1.4,3.2,1,6]
length*width

TypeError: can't multiply sequence by non-int of type 'list'

In [9]:
import numpy as np
np_length=np.array(length) #np_length is numpy array
print(np_length)

[2 4 6 8]


In [10]:
type(np_length)

numpy.ndarray

In [11]:
type(length)

list

In [12]:
print(np_length+1)

[3 5 7 9]


In [13]:
print(np_length*2)

[ 4  8 12 16]


In [14]:
print(np_length+np_length)

[ 4  8 12 16]


In [15]:
np_width=np.array(width)
print(np_length*np_width)

[ 2.8 12.8  6.  48. ]


In [28]:
baseball_h=np.array([72,78,69,71,76,79])
height_m=baseball_h*.0254
print(height_m)

[1.8288 1.9812 1.7526 1.8034 1.9304 2.0066]


In [25]:
baseball_w=np.array([180,215,210,188,176,209])
weight_kg=baseball_w*.453592

print(weight_kg)

[81.64656  97.52228  95.25432  85.275296 79.832192 94.800728]


In [29]:
BMI=weight_kg/height_m**2
print(BMI)

[24.41211827 24.84546948 31.01123531 26.22038745 21.42315531 23.54453169]


In [30]:
print(np.round(BMI,3))

[24.412 24.845 31.011 26.22  21.423 23.545]


In [31]:
x=[4,9,6,3,1]
print(x[1])

9


In [34]:
y=np.array(x)
print(y)

[4 9 6 3 1]


In [35]:
print(y[1])

9


In [36]:
print(y[1:3])

[9 6]


In [37]:
print(y[3:])

[3 1]


In [38]:
print(y[-2])

3


In [39]:
#for numpy only
#cant use for list
my_index=np.array([True,True,False,False,True])
y[my_index]
print(y[my_index])

[4 9 1]


In [40]:
y>5

array([False,  True,  True, False, False])

In [41]:
high=y>5
print(y[high])

[9 6]


In [42]:
y==1


array([False, False, False, False,  True])

In [43]:
y!=1

array([ True,  True,  True,  True, False])

In [44]:
print(y)

[4 9 6 3 1]


In [45]:
sub_y=y[[0,4,2]]
print(sub_y)

[4 1 6]


In [46]:
list_2d=[[72,78,69,71,76,79],[180,215,210,188,176,209]]
np_2d=np.array(list_2d)
print(np_2d)

[[ 72  78  69  71  76  79]
 [180 215 210 188 176 209]]


In [48]:
np_2d.shape

(2, 6)

In [49]:
np_2d[0,2]

69

In [50]:
np_2d[0,2:4]

array([69, 71])

In [51]:
np_2d[:,2:4]

array([[ 69,  71],
       [210, 188]])

In [52]:
np_2d[0,:]

array([72, 78, 69, 71, 76, 79])

In [53]:
np_2d[0,[0,2,3]]

array([72, 69, 71])

In [54]:
from sklearn.datasets import load_iris
iris=load_iris()
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [55]:
iris_attr=iris.data
print(iris_attr)
print(iris.feature_names)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [56]:
species=iris.target
print(species)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [57]:
np_iris=np.array(iris_attr)
print(np_iris)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [80]:
iris_attr.shape

(150, 4)

In [82]:
iris_attr[2,:]

array([4.7, 3.2, 1.3, 0.2])

In [83]:
sepal_width=iris_attr[:,1]

In [62]:
np_iris[:,1]

array([3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
       3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       3.4, 3.5, 3.4, 3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.6, 3. ,
       3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3. , 3.8, 3.2, 3.7, 3.3, 3.2, 3.2,
       3.1, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2. , 3. , 2.2, 2.9, 2.9,
       3.1, 3. , 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 2.8, 2.9, 3. , 2.8, 3. ,
       2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3. , 3.4, 3.1, 2.3, 3. , 2.5, 2.6,
       3. , 2.6, 2.3, 2.7, 3. , 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3. , 2.9,
       3. , 3. , 2.5, 2.9, 2.5, 3.6, 3.2, 2.7, 3. , 2.5, 2.8, 3.2, 3. ,
       3.8, 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3. , 2.8, 3. ,
       2.8, 3.8, 2.8, 2.8, 2.6, 3. , 3.4, 3.1, 3. , 3.1, 3.1, 3.1, 2.7,
       3.2, 3.3, 3. , 2.5, 3. , 3.4, 3. ])

In [84]:
iris_attr[94,2]

4.2

In [87]:
species=iris.target
index=species==1
iris_attr[index,:]
#or 
iris_attr[species==1,:]


array([[7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3

In [92]:
versicolor=iris_attr[index,:]
print(np.mean(versicolor[:,2]))
#or
print(np.mean(iris_attr[index,2]))

4.26
4.26


In [89]:

a=1

In [93]:
# declaring function definition
def printme(str):
    print(str)
    return

In [95]:
#calling a function
printme('adadhfjfj')
print('ahdhd')

adadhfjfj
ahdhd


In [101]:
def printinfo(name,age):
    print('Name',name)
    print('Age',age)
    return

In [102]:
printinfo('lucy',80)

Name lucy
Age 80


In [103]:
printinfo(age=80,name='lucy')

Name lucy
Age 80


In [104]:
def add(a,b):
    print(a+b)
    return

In [105]:
add(1,3)

4


In [106]:
sum_v=add(1,3)
print(sum_v)

4
None


In [3]:
def add(a,b):
    a+b
    return a+b

In [6]:
sum_v=add(1,3)
print(sum_v)

4
